Name: S.Ch.Gowtham Yarlagadda

Role: Machine Learning intern

Ph:   8309051780

## Resume Filtering

Instead of using Sword (Machine learning) for a cake (Resume filtering), I've decided to use pandas, openpyxl modules and an algorithm named KMP. It seemed simpler that way.(At First! lol)

KMP Algorithm for keyword matching

In [1]:
# KMP Algorithm

def KMP(pat, txt):
	M = len(pat)
	N = len(txt)
	flag=False

	lps = [0]*M
	j = 0 
	computeLPSArray(pat, M, lps)

	i = 0 
	while (N - i) >= (M - j):
		if pat[j] == txt[i]:
			i += 1
			j += 1

		if j == M:
			flag=True
			j = lps[j-1]

		elif i < N and pat[j] != txt[i]:
			if j != 0:
				j = lps[j-1]
			else:
				i += 1
	return(flag)

def computeLPSArray(pat, M, lps):
	len = 0 
	lps[0] = 0 
	i = 1

	while i < M:
		if pat[i] == pat[len]:
			len += 1
			lps[i] = len
			i += 1
		else:
			if len != 0:
				len = lps[len-1]

			else:
				lps[i] = 0
				i += 1

# if __name__=='__main__':
    
# 	txt = "ABABDABACDABABCABAB"
# 	pat = "ABABCABAB"
    
# 	KMP(pat, txt)

# Importing modules and files

In [2]:

import openpyxl

excel_file_path = "C:/Users/gowth/Downloads/excelfile1.xlsx"

file=openpyxl.load_workbook(excel_file_path)

filtered_candidates = []
sheet=file.worksheets[0]

# Cutoffs

In [3]:
min_py=2
min_ml=1
min_nlp=1
min_dl=1
availabilty = ['Yes, I am available for 3 months']
degree = ['Data Science','Computer Science','B.E','B.Tech','Bachelor of Technology','Artificial Intelligence','Computer','B.Sc','BE','Bachelor of Technology','Data Scientist','M.Sc','M.Tech','MCA','Diploma','M.C.S','MS','M.E']
min_grad_year=2022

desired_keywords_tech = ['Python', 'Machine Learning', 'Natural Language Processing', 'Deep Learning']
desired_keywords_soft = ['English']

min_total_academic_score = 70 #50 percent

# Tools

Skill Filtering tool

In [4]:
def tech_skills_filtering(row):
    flag = False
    if row[1] is not None and row[2] is not None and row[3] is not None and row[4] is not None:
        if row[1] >= min_py and row[2] >= min_ml and row[3] >= min_nlp and row[4] >= min_dl:
            flag = True
    return flag

Softskill filtering tool

In [5]:
def keyword_matching_tool_soft(row):
    flag = False
    if row[5] is not None:
        for keyword in desired_keywords_soft:
            if KMP(keyword.lower(), row[5].lower()):
                flag = True
    return flag

Technical Skills filtering Tool

In [6]:
def keyword_matching_tool_tech(row):
    flag=False
    if row[5] is not None:
        for keyword in desired_keywords_tech:
            if KMP(keyword.lower(),row[5].lower()) == True:
                flag=True
    return flag

Availability filtering tool

In [7]:
def keyword_matching_tool_availability(row):
    flag=False
    if row[6] is not None:
        for keyword in availabilty:
            if KMP(keyword.lower(),row[6].lower()) == True:
                flag=True
    return flag

Degree Filtering tool

In [8]:
def keyword_matching_tool_degree(row):
    flag=False
    if row[7] is not None:
        for keyword in degree:
            if KMP(keyword.lower(),row[7].lower()) == True:
                flag=True
    return flag

Calculating total academic score and making it's filtering tool

In [9]:
from decimal import Decimal
def calculate_academic_score(row_number):
    sheet=file.worksheets[0]
    marks=[]
    for row in sheet[2:1137]:

        if row[row_number].value != 'N/A' or None: 
            value = row[row_number].value.replace(',', '')  # Remove any commas if present
            numerator, denominator = value.split('/')  # Split the string into numerator and denominator
            if Decimal(numerator)!=Decimal(denominator):
                fraction = Decimal(numerator) / Decimal(denominator)
            else:
                fraction= Decimal(numerator)/10
        
            if fraction>1:
                fraction=fraction*10
            elif fraction<0.1:
                fraction=fraction*1000
            else:
                fraction=fraction*100
            marks.append(fraction)
        else:
            marks.append(0)
    return marks

pg_marks=calculate_academic_score(10)
ug_marks=calculate_academic_score(11)
inter_marks=calculate_academic_score(12)
tenth_marks=calculate_academic_score(13)

total_scores=[0]*sheet.max_row

for i in range(len(pg_marks)):
    
    if pg_marks[i]==0:
        total_scores[i]=(ug_marks[i]+inter_marks[i]+tenth_marks[i])/3
    else:
        total_scores[i]=(pg_marks[i]+ug_marks[i]+inter_marks[i]+tenth_marks[i])/4
        




def total_academic_score(x):
    flag=False
    if total_scores[x] is not None and total_scores[x]>= min_total_academic_score:
        flag=True
    return flag

# Filtering Process

In [10]:
filtered_candidates = []
row_index=0
for row in sheet.iter_rows(min_row=2, values_only=True):
    
    if total_academic_score(row_index) and tech_skills_filtering(row) and keyword_matching_tool_soft(row) and keyword_matching_tool_tech(row) and keyword_matching_tool_availability(row) and keyword_matching_tool_degree(row):
        filtered_candidates.append(row)
    row_index+=1

# Qualified Candidates

In [11]:
import pandas as pd
from IPython.display import display

# Create a DataFrame from the filtered_candidates data
df = pd.DataFrame(filtered_candidates, columns=['Name', 'Python (out of 3)','Machine Learning (out of 3)','Natural Language Processing (NLP) (out of 3)','Deep Learning (out of 3)','Other skills','Are you available for 3 months, starting immediately, for a full-time work from home internship? ','Degree','Stream','Current Year Of Graduation','Performance_PG','Performance_UG', 'Performance_12','Performance_10'])  

# Display the DataFrame
display(df)

,Name,Python (out of 3),Machine Learning (out of 3),Natural Language Processing (NLP) (out of 3),Deep Learning (out of 3),Other skills,"Are you available for 3 months, starting immediately, for a full-time work from home internship?",Degree,Stream,Current Year Of Graduation,Performance_PG,Performance_UG,Performance_12,Performance_10
0,1,3,3,3,2,"Data Analytics, Data Science, English Proficie...","Yes, I am available for 3 months starting imme...",Advanced Certification In Data Science,Data Analytics,2023,N/A,9.00/9,60.00/60.00,70.00/70.00
1,55,3,3,1,2,"Data Analytics, Data Science, English Proficie...","Yes, I am available for 3 months starting imme...",B.Tech,Computer Science,2024,N/A,7.51/10,89.60/89.60,91.00/91.00
2,80,2,2,2,1,"English Proficiency (Spoken), English Proficie...","Yes, I am available for 3 months starting imme...",B.Tech,None,2024,N/A,9.12/10,92.00/92.00,90.60/90.60
3,91,2,3,2,2,"Algorithms, Amazon Web Services (AWS), C++ Pro...","Yes, I am available for 3 months starting imme...",B.Tech,Computer Science With Specialization In Data S...,2024,N/A,8.80/10,91.50/91.50,9.40/9.40
4,113,2,2,2,2,"American English, English Proficiency (Spoken)...","Yes, I am available for 3 months starting imme...",B.Tech,Computer Science,2024,N/A,7.86/10,88.67/88.67,93.67/93.67
5,175,3,3,2,2,"Data Analytics, English Proficiency (Spoken), ...","Yes, I am available for 3 months starting imme...",B.Tech,Artificial Intelligence And Data Science,2024,N/A,9.11/10,92.20/92.20,96.00/96.00
6,188,3,3,2,2,".NET, Adobe XD, Amazon Web Server (AWS), Artif...","Yes, I am available for 3 months starting imme...",B.Tech,Computer Science & Engineering,2024,N/A,9.40/10,91.80/91.80,10.00/10.00
7,190,3,2,2,2,"English Proficiency (Spoken), English Proficie...","Yes, I am available for 3 months starting imme...",B.Tech,computer science,2023,N/A,8.17/10,62.92/62.92,93.60/93.60
8,244,2,2,2,1,"English Proficiency (Spoken), English Proficie...","Yes, I am available for 3 months starting imme...",B.Tech,Computer Science,2024,N/A,3.60/4,85.00/85.00,85.00/85.00
9,269,2,2,1,1,"English Proficiency (Spoken), English Proficie...","Yes, I am available for 3 months starting imme...",B.Tech,Computer Science And Engineering( Data Science),2025,N/A,9.08/10,98.00/98.00,97.20/97.20
10,367,2,1,1,1,"English Proficiency (Written), Python, CSS, Da...","Yes, I am available for 3 months starting imme...",B.Tech,Data Science,2024,N/A,9.00/10,75.00/75.00,80.00/80.00
11,369,2,2,1,2,"English Proficiency (Spoken), English Proficie...","Yes, I am available for 3 months starting imme...",B.Tech,None,2024,N/A,8.55/10,8.00/8.00,8.40/8.40
12,442,2,1,1,1,"English Proficiency (Written), Artificial inte...","Yes, I am available for 3 months starting imme...",B.Tech,Computer Science & Engineering In Specialisati...,2024,N/A,8.28/10,87.50/87.50,82.60/82.60
13,587,3,2,1,2,"English Proficiency (Written), Python, BIG DAT...","Yes, I am available for 3 months starting imme...",Bachelor of Engineering (B.E),Information Technology,2024,N/A,9.60/10,66.62/66.62,83.80/83.80
14,609,2,1,1,2,"HTML, Bootstrap, C Programming, C++ Programmin...","Yes, I am available for 3 months starting imme...",Bachelor of Engineering (B.E),computer science,2023,N/A,9.10/10,98.10/98.10,10.00/10.00
15,728,2,2,1,1,"C Programming, Content Writing, Database Manag...","Yes, I am available for 3 months starting imme...",Bachelor of Technology (B.Tech),Computer Science & Engineering,2024,N/A,8.48/10,91.40/91.40,95.20/95.20
16,766,2,2,1,2,"Deep Learning, English Proficiency (Spoken), E...","Yes, I am available for 3 months starting imme...",Bachelor of Technology (B.Tech),Chemical Engineering,2025,N/A,6.88/10,82.20/82.20,94.40/94.40
17,796,2,2,1,2,"Content Writing, English Proficiency (Spoken),...","Yes, I am available for 3 months starting imme...",Bachelor of Technology (B.Tech),"Computer Science & Engineering, Specializing I...",2024,N/A,9.00/10,75.30/75.30,82.00/82.00
18,931,3,3,2,2,"Computer Vision, Data Science, English Profici...","Yes, I am available for 3 months starting imme...",Master of Computer Applications (MCA),Artificial Intelligence,2023,N/A,7.30/10,9.40/9.40,9.30/9.30
19,984,3,3,3,3,"Deep Learning, Flask, Hadoop, JavaScript, Mach...","Yes, I am available for 3 months starting imme...",Master of Science (M.Sc),Economics,2023,8.16/10,8.10/10,82.20/82.20,84.40/84.40

Above results can be decreased or increased by changing cuttoffs! Thank you...

Technical skills and softskills(mainly) can be known further in the interviews or tests conducted in online platforms like HackerRank, Codility, SHL, etc.

I didn't understand the last part of the project, Is there a spreadsheet for that?